version: 1

validators:
  - regex: 'localhost'
    type: 'ignore'
  - regex: 'envoyproxy'
    type: 'ignore'
  - regex: 'deno\.land'
    type: 'ignore'
  - regex: 'twitter\.com'
    type: 'ignore'
  - regex: 'rhobs'
    type: 'ignore'
  - regex: 'prometheus\.io'
    type: 'ignore'
  - regex: 'thanos\.io'
    type: 'ignore'